include $(GNUSTEP_MAKEFILES)/common.make

APP_NAME = SimpleAutolayoutTest
SimpleAutolayoutTest_HEADERS = AppDelegate.h AppWindow.h BackgroundColorView.h
SimpleAutolayoutTest_OBJC_FILES = main.m AppWindow.m AppDelegate.m BackgroundColorView.m

include $(GNUSTEP_MAKEFILES)/application.make
